version: '3.9'
services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file: ".env"
    depends_on:
      - mongo
    volumes:
      - ./server:/app
    command: ["node", "server.js"]

  frontend:
    build:
      context: ./client/react
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./client/react:/app
    stdin_open: true
    tty: true
    command: ["npm", "run", "dev"]

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
