version: '3.9'
services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.server
    ports:
      - "8080:8080"
    env_file: ".env"
    depends_on:
      - mongo
    volumes:
      - ./server:/app
    command: ["npm", "run", "start"]

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
    stdin_open: true
    tty: true
    command: ["npm", "run", "dev"]

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
