version: '3.9'
services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file: "./server/.env"
    image: mern_project/server:1.0
    volumes:
      - ./server:/server
    command: ["node", "server.js"]

  frontend:
    build:
      context: ./client/react
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./client/react:/react
    stdin_open: true
    environment:
      - VITE_API_BASE_URL=http://backend:8080
    image: mern_project/client:1.0
    tty: true
    command: ["npm", "run", "dev"]

networks:
  app-network:
    driver: bridge