version: '3.9'
services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file: ".env"
    volumes:
      - server_side:./server
    command: ["node", "server.js"]

  frontend:
    build:
      context: ./client/react
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - client_side:./client/react
    stdin_open: true
    tty: true
    command: ["npm", "run", "dev"]
    
networks:
  app-network:
    driver: bridge