# Build Stage
FROM node
WORKDIR /server
# Copy package.json and package-lock.json to the working directory
COPY package*.json /server
RUN npm install
# Copies the entire application code to the working directory.
COPY . /server
# Specifies the command to run when the container starts (node server.js).
CMD ["node","server.js"]